POST http://localhost:3003/api/blogs/6a089b540ada307c7d601dfc/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJhcnJlbnQiLCJpZCI6IjZhMDg5YjBkMGFkYTMwN2M3ZDYwMWRmYiIsImlhdCI6MTc3ODk0ODkxM30.glZZWHiYs-LxPTP-9lpeA91X5uoLJtrweywWf0k0RNE

{
    "comment": "New Comment 2"
}